server {
    listen 80;

    location /iss {
        alias /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /iss/index.html;

        location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}
